/**
 * All user-facing UI strings live here (Russian). Components must not
 * hardcode text — import from this file so copy stays in one place.
 */
export const strings = {
  app: {
    name: "Pathway",
  },
  common: {
    close: "Закрыть",
    back: "Назад",
    next: "Далее",
    skip: "Пока не знаю",
    save: "Сохранить",
    saving: "Сохраняю…",
    saved: "Сохранено",
    cancel: "Отмена",
    undo: "Вернуть",
    add: "Добавить",
    delete: "Удалить",
    edit: "Изменить",
    other: "Другой",
    done: "Готово",
    optional: "необязательно",
    moveUp: "Выше",
    moveDown: "Ниже",
    errorGeneric: "Не удалось сохранить. Попробуйте ещё раз.",
    loading: "Загружаем…",
  },
  preference: {
    freeOnly: "Только бесплатно / грант",
    freeOnlyHint: "В каталоге и возможностях останутся варианты без платы или с грантом.",
  },
  fit: {
    category: {
      dream: "Мечта",
      target: "Цель",
      safety: "Запасной",
    },
    check: {
      meets: "Подходит",
      below: "Ниже требования",
      unknown: "Нет данных",
      not_required: "Нет требования",
    },
  },
  nav: {
    dashboard: "Дашборд",
    profile: "Профиль",
    cv: "Резюме",
    universities: "Университеты",
    roadmap: "Дорожная карта",
    tasks: "Задачи",
    agent: "Агент",
    mentors: "Наставники",
    impact: "Импакт",
    signOut: "Выйти",
  },
  landing: {
    title: "Pathway",
    tagline:
      "Поступление в университет — это план, а не догадка. Pathway строит его для тебя.",
    howItWorksTitle: "Как это работает",
    steps: [
      {
        title: "Расскажи о себе",
        description:
          "Оценки, экзамены, интересы и страны, куда хочешь поступать.",
      },
      {
        title: "Получи подбор вузов",
        description:
          "Мечта, Цель и Запасной — по реальным требованиям, без выдуманных шансов.",
      },
      {
        title: "Следуй плану",
        description:
          "Еженедельные задачи и трекер, чтобы не пропустить дедлайны.",
      },
    ],
    ctaStart: "Начать",
    ctaLogin: "Войти",
    ctaDashboard: "Открыть кабинет",
  },
  auth: {
    login: {
      title: "Вход",
      subtitle: "Войдите в свой аккаунт Pathway",
      emailLabel: "Email",
      passwordLabel: "Пароль",
      submit: "Войти",
      submitting: "Входим…",
      noAccount: "Нет аккаунта?",
      signupLink: "Зарегистрироваться",
    },
    signup: {
      title: "Регистрация",
      subtitle: "Создайте аккаунт, чтобы начать путь к поступлению",
      fullNameLabel: "Имя и фамилия",
      emailLabel: "Email",
      passwordLabel: "Пароль",
      submit: "Зарегистрироваться",
      submitting: "Создаём аккаунт…",
      haveAccount: "Уже есть аккаунт?",
      loginLink: "Войти",
    },
    errors: {
      invalidCredentials: "Неверный email или пароль.",
      emailAlreadyRegistered: "Этот email уже зарегистрирован.",
      network:
        "Не удалось связаться с сервером. Проверьте подключение к интернету и попробуйте снова.",
      generic: "Что-то пошло не так. Попробуйте снова.",
      fullNameRequired: "Введите имя и фамилию.",
      emailRequired: "Введите email.",
      emailInvalid: "Введите корректный email.",
      passwordRequired: "Введите пароль.",
      passwordWeak:
        "Пароль должен содержать минимум 8 символов, включая хотя бы одну букву и одну цифру.",
    },
  },
  dashboard: {
    greeting: (name: string) => `Привет, ${name}`,
    onboardingDone: "Онбординг завершён",
    onboardingPending: "Онбординг не завершён",
    onboardingCta: "Пройти онбординг",
    completenessTitle: (percent: number) => `Профиль заполнен на ${percent}%`,
    completenessCta: "Заполнить недостающее",
    completenessDone: "Профиль заполнен",
    headlineProfile: "Начнём с профиля — дорога откроется после него.",
    headlineCv: "Профиль готов — теперь резюме.",
    headlineUnis: "Дальше — выбери вузы.",
    headlineNext: "Шортлист уже есть. Дальше — экзамены и заявки.",
    levelReady: "Профиль заполнен",
    levelGap: (countLabel: string) => `до уровня «Готов» — ${countLabel}`,
    readiness: "Готовность",
    littleData: "Нет данных",
    achievements: "Отметки",
    weeklyGoal: "Цель на неделю",
    weeklyGoalHint: "Сколько задач закрыть на этой неделе",
    weeklyGoalSave: "Сохранить",
    weeklyGoalSaved: "Цель на неделю сохранена",
    weeklyGoalClear: "Сбросить",
    weeklySummary: (due: number, done: number) => `На этой неделе: ${done} из ${due} по сроку.`,
    favoritesTile: "в списке",
    chancesEmpty: "Пока нет вузов в списке",
    chancesEmptyText: "Разложим выбранные вузы на «Мечта», «Цель» и «Запасной».",
    chancesCta: "Выбрать вузы",
    aiMessage: "Могу разобрать план, дедлайны и пробелы по вузам. Напиши, с чего начать.",
    aiCta: "Спросить помощника",
    aiTasks: "К задачам",
    quest: "Цель недели",
  },
  soon: {
    title: "Скоро здесь…",
    body: "Этот раздел ещё собирается.",
  },
  favorites: {
    title: "Избранное",
    count: (count: number, word: string) => `В шортлисте ${count} ${word}.`,
    unavailable: "Не удалось загрузить шортлист.",
    empty: "Пока нет вузов в списке.",
    emptyCta: "Выбрать вузы",
    emptyGroup: "Пока пусто в этой группе.",
    groupHeading: (name: string, count: number) => `${name} · ${count}`,
    badge: (count: number) => `${count} в избранном`,
    toCompare: "Сравнить",
  },
  whatIf: {
    title: "Что если",
    hint: "Двигай баллы — профиль не сохраняется. Смотрим, как меняется категория.",
    gpa: "GPA",
    scale: "шкала",
    improved: (n: number) => `Категория лучше у ${n} вузов`,
    dropped: (n: number) => `Категория ниже у ${n} вузов`,
    grants: (n: number) => `Грантовых вузов с закрытыми требованиями: +${n}`,
    none: "По этим баллам категории не меняются.",
    fromTo: (from: string, to: string) => `${from} → ${to}`,
    shortlist: "Избранное",
    catalog: "Каталог",
  },
  compare: {
    title: "Сравнение",
    pick: "Выбери 2–4 вуза из списка",
    show: "Сравнить",
    needTwo: "Добавь хотя бы два вуза в избранное, чтобы сравнить.",
    metric: "Параметр",
    list: "В списке",
  },
  universities: {
    title: "Вузы",
    search: "Название или город",
    region: "Регион",
    country: "Страна",
    field: "Специальность",
    deadline: "Дедлайн",
    all: "Все",
    upcoming: "Ближайшие",
    lastCycle: "Прошлый цикл",
    apply: "Показать",
    reset: "Сбросить",
    empty: "Нет вузов по этим фильтрам.",
    emptyCta: "Сбросить фильтры",
    add: "В список",
    remove: "Убрать",
    removed: "Убрали из списка",
    source: "Источник",
    website: "Сайт вуза",
    cost: "Стоимость",
    grants: "Гранты",
    tuitionUnknown: "Стоимость не указана",
    freeTuition: "Бесплатно",
    perYear: "в год",
    fitTitle: "Соответствие",
    gapsTitle: "Что закрыть",
    deadlinesTitle: "Дедлайны",
    noGaps: "По известным данным пробелов нет.",
    noDeadlines: "Дедлайнов в базе нет.",
    littleData: "Нет данных",
    score: (n: number) => `${n}`,
    have: "у тебя",
    need: "нужно",
    verify: "проверьте на сайте вуза",
    regions: {
      kazakhstan: "Казахстан",
      usa: "США",
      uk: "Великобритания",
      europe: "Европа",
      asia_other: "Азия",
    },
    aid: {
      need_blind: "Без учёта дохода",
      need_aware: "С учётом дохода",
      merit: "За успехи",
      none: "без гранта для иностранцев",
      unknown: "помощь неизвестна",
      funded: "С финансированием",
    },
    hintCategory: "подсказка движка",
    pathTitle: "Кратчайший путь сюда",
    pathEmpty: "Уже лучшая категория по известным требованиям.",
    pathAdd: "Добавить в план",
    pathAdded: (inserted: number, unchanged: number) =>
      inserted > 0 ? `Добавлено ${inserted}, уже было ${unchanged}.` : "Эти шаги уже в плане.",
    pathWeeks: (n: number) => `${n} нед.`,
    pathAlt: "Другие варианты",
    checks: {
      english: "Английский",
      unt: "ЕНТ",
      sat: "SAT",
      gpa: "GPA",
      budget: "Бюджет",
      major: "Специальность",
      country: "Страна",
      deadline: "Дедлайн",
    },
  },
  opportunities: {
    title: "Возможности",
    empty: "Пока нет подходящих возможностей.",
    emptyCta: "Дополнить профиль",
    type: "Тип",
    format: "Формат",
    upcoming: "Только с открытым дедлайном",
    apply: "Показать",
    reset: "Сбросить",
    source: "Источник",
    types: {
      olympiad: "Олимпиада",
      summer_program: "Летняя программа",
      internship: "Стажировка",
      competition: "Конкурс",
      research: "Исследование",
      scholarship: "Стипендия",
      course: "Курс",
    },
    formats: {
      online: "Онлайн",
      in_person: "Очно",
      hybrid: "Гибрид",
      unknown: "Формат не указан",
    },
  },
  exams: {
    title: "Экзамены",
    empty: "Добавь вузы в список — появится план подготовки.",
    emptyCta: "Выбрать вузы",
    weeks: (n: number) => `${n} нед. до дедлайна`,
    noWeeks: "Дата на сайте вуза",
    target: "Ориентир",
    current: "Сейчас",
    noScore: "ещё нет балла",
    forUniversity: "для",
    plan: "План",
    week: (n: number) => `Неделя ${n}`,
    resources: "Материалы",
  },
  roadmap: {
    title: "Дорожная карта",
    empty: "Добавь вузы в список — появится план на недели.",
    emptyCta: "Выбрать вузы",
    sync: "Собрать план в задачи",
    synced: (inserted: number, updated: number) =>
      `Добавлено ${inserted}, обновлено ${updated}.`,
  },
  tasks: {
    title: "Задачи",
    empty: "Пока нет задач. Соберите план или добавьте свою.",
    emptyCta: "Открыть план",
    add: "Добавить",
    deleted: "Задача удалена",
    titleRequired: "Введите название.",
    name: "Название",
    due: "Срок",
    notes: "Заметка",
    delete: "Удалить",
    thisWeek: "Эта неделя",
    noDate: "Без даты",
    weekFrom: (d: string) => `Неделя с ${d}`,
    status: {
      todo: "К делу",
      in_progress: "В работе",
      done: "Готово",
    },
    source: {
      roadmap: "План",
      agent: "Помощник",
      manual: "Своя",
    },
  },
  assistant: {
    title: "AI-помощник",
    empty: "Спроси про вуз, дедлайн или задачу — отвечу по данным Pathway.",
    placeholder: "Напиши вопрос",
    send: "Отправить",
    stop: "Стоп",
    unavailable: "Помощник сейчас недоступен. Попробуй позже.",
    tryAgain: "Попробуй ещё раз",
    label: "AI-помощник · ИИ, не человек",
  },
  mentors: {
    title: "Наставники",
    empty: "Пока нет вопросов. Задай первый — наставник ответит.",
    ask: "Задать вопрос",
    answerNote: "Отвечать могут только проверенные наставники.",
    emptyAnswers: "Пока нет ответов.",
    titleLabel: "Заголовок",
    bodyLabel: "Вопрос",
    tagsLabel: "Теги",
    tagsHint: "Через запятую",
    answer: "Ответить",
    answerLabel: "Ответ",
    badge: "Ментор",
    participant: "Участник",
    answers: "Ответы",
  },
  impact: {
    title: "Импакт",
    empty: "Сводка пока недоступна.",
    users: "Пользователи",
    onboarded: "Онбординг пройден",
    shortlist: "Вузы в списках",
    roadmapDone: "Задачи плана закрыты",
    cvs: "Резюме заполнены",
    answers: "Ответы наставников",
    readiness: "Входы готовности",
    withGpa: "с GPA",
    withExams: "с экзаменами",
    withShortlist: "со списком вузов",
    withCv: "с резюме",
    feedback: "Отзывы",
    feedbackAvg: "Средняя оценка",
    feedbackNone: "Пока нет отзывов",
  },
  feedback: {
    title: "Помогло ли тебе?",
    hint: "Оценка от 1 до 5.",
    score: (n: number) => `${n} из 5`,
    comment: "Комментарий",
    submit: "Отправить",
    thanks: "Спасибо за отзыв.",
    pick: "Выбери оценку.",
  },
  credits: {
    link: "Фото и лицензии",
  },
  guide: {
    title: "Как пользоваться Pathway",
    intro: "Короткий маршрут: сначала профиль, потом вузы и план.",
    steps: [
      {
        href: "/profile",
        title: "Профиль",
        text: "Класс, оценки, язык, страны и бюджет — шансы считаем по этим данным.",
      },
      {
        href: "/universities",
        title: "Вузы и шансы",
        text: "Каталог и проверка требований. На карточке вуза — кратчайший путь.",
      },
      {
        href: "/favorites",
        title: "Избранное и сравнение",
        text: "Сохрани Мечту, Цель и Запасной, сравни два вуза рядом.",
      },
      {
        href: "/universities",
        title: "Кратчайший путь",
        text: "Открой вуз: что подтянуть, чтобы шагнуть в следующую категорию.",
      },
      {
        href: "/what-if",
        title: "Что если",
        text: "Подвинь баллы без сохранения — как меняются категории вузов.",
      },
      {
        href: "/roadmap",
        title: "План и задачи",
        text: "Собери дорожную карту и закрой задачи по неделям.",
      },
      {
        href: "/opportunities",
        title: "Возможности",
        text: "Олимпиады и программы под твой класс — без выдуманных цифр.",
      },
      {
        href: "/assistant",
        title: "Ассистент",
        text: "Спроси про вуз, дедлайн или задачу. Отвечает по базе Pathway.",
      },
    ],
  },
  onboarding: {
    title: "Расскажите о себе",
    progress: (step: number, total: number) => `Шаг ${step} из ${total}`,
    road: [
      "Статус",
      "Город",
      "Направление",
      "Страны",
      "Бюджет",
      "Английский",
      "Экзамены",
      "Оценки",
      "Год",
      "Итог",
    ],
    noteEditable: "ответы можно поменять",
    growing: "Профиль растёт",
    complete: "Готово",
    completing: "Сохраняем…",
    completeBlocked: "Сначала заполните обязательные шаги.",
    steps: {
      status: {
        title: "Кто вы?",
        legend: "Статус",
        graduate: "Школьник-выпускник",
        graduateHint: "9–12 класс, готовлюсь к поступлению",
        transfer: "Перевод из вуза",
        transferHint: "Уже учусь и хочу перевестись",
        gradeLegend: "Класс или курс",
      },
      city: {
        title: "Из какого вы города?",
        legend: "Город",
        otherLabel: "Укажите город",
        otherPlaceholder: "Название города",
      },
      major: {
        title: "Какое направление интересует?",
        legend: "Направление",
        otherLabel: "Своё направление",
        otherPlaceholder: "Например, биоинженерия",
      },
      countries: {
        title: "Куда хотите поступать?",
        legend: "Страны",
        hint: "Можно выбрать несколько. Значения совпадают с каталогом вузов.",
      },
      budget: {
        title: "Какой бюджет на год обучения?",
        legend: "Бюджет в год, $",
        scholarship: "Нужна стипендия",
        ranges: {
          zero: "Только гранты",
          upTo10k: "до 10 000 $",
          from10to20: "10 000–20 000 $",
          from20to40: "20 000–40 000 $",
          from40to60: "40 000–60 000 $",
          from60plus: "60 000 $ и больше",
        },
      },
      english: {
        title: "Какой у вас английский?",
        legend: "Уровень английского",
        examsHint: "Если есть баллы языковых экзаменов — добавьте их ниже.",
        levels: {
          none: "Не изучал / не знаю",
          noneHint: "Английский пока не оценивал",
          A1: "A1 — начальный",
          A1Hint: "Простые фразы и знакомство",
          A2: "A2 — базовый",
          A2Hint: "Могу объясниться в быту",
          B1: "B1 — средний",
          B1Hint: "Могу учиться с поддержкой",
          B2: "B2 — выше среднего",
          B2Hint: "Готов к учёбе на английском",
          C1: "C1 — продвинутый",
          C1Hint: "Свободно читаю и пишу академические тексты",
          C2: "C2 — в совершенстве",
          C2Hint: "Уровень носителя",
        },
      },
      exams: {
        title: "Какие экзамены вы сдавали или планируете?",
        legend: "Экзамены",
        hint: "ЕНТ — для вузов Казахстана, SAT и другие — по желанию.",
      },
      gpa: {
        title: "Какая у вас успеваемость?",
        legend: "Средний балл",
        gpaLabel: "GPA / средний балл",
        scaleLabel: "Шкала",
      },
      intakeYear: {
        title: "На какой год поступления целитесь?",
        legend: "Год поступления",
      },
      summary: {
        title: "Проверьте ответы",
        hint: "Можно вернуться к любому шагу и поправить.",
        empty: "Не указано",
        fields: {
          status: "Статус",
          city: "Город",
          major: "Направление",
          countries: "Страны",
          budget: "Бюджет",
          scholarship: "Нужна стипендия",
          english: "Английский",
          exams: "Экзамены",
          gpa: "Успеваемость",
          intakeYear: "Год поступления",
        },
        yes: "Да",
        no: "Нет",
      },
    },
  },
  profile: {
    title: "Профиль",
    save: "Сохранить профиль",
    saved: "Профиль сохранён",
    saveError: "Не удалось сохранить профиль.",
    checkFields: "Проверьте отмеченные поля",
    sections: {
      basics: "Основное",
      goals: "Цели",
      budget: "Бюджет",
      english: "Английский и экзамены",
      academics: "Успеваемость",
    },
    fields: {
      fullName: "Имя и фамилия",
      path: "Статус",
      grade: "Класс или курс",
      city: "Город",
      major: "Направление",
      countries: "Страны",
      budget: "Бюджет в год, $",
      scholarship: "Нужна стипендия",
      english: "Уровень английского",
      exams: "Экзамены",
      gpa: "GPA / средний балл",
      gpaScale: "Шкала",
      intakeYear: "Год поступления",
    },
    exam: {
      add: "Добавить экзамен",
      code: "Экзамен",
      score: "Балл",
      grade: "Оценка",
      subject: "Предмет",
      status: "Статус",
      date: "Дата",
      taken: "Сдан",
      planned: "Планирую",
      remove: "Удалить экзамен",
      names: {
        IELTS: "IELTS",
        TOEFL_IBT: "TOEFL iBT",
        DET: "Duolingo",
        SAT: "SAT",
        ACT: "ACT",
        AP: "AP",
        IB_DP: "IB",
        A_LEVEL: "A-Level",
        UNT: "ЕНТ",
        NUET: "NUET",
      },
    },
    errors: {
      pathRequired: "Выберите статус.",
      gradeRequired: "Выберите класс или курс.",
      gradeMismatch: "Выберите класс или курс, подходящий к вашему статусу.",
      cityRequired: "Укажите город.",
      cityOtherRequired: "Укажите свой город.",
      majorRequired: "Укажите направление.",
      majorOtherRequired: "Укажите своё направление.",
      countriesRequired: "Выберите хотя бы одну страну.",
      budgetInvalid: "Бюджет не может быть отрицательным.",
      englishRequired: "Выберите уровень английского.",
      gpaInvalid: "Введите корректный средний балл.",
      gpaScaleInvalid: "Выберите шкалу: 4, 5, 10 или 100.",
      gpaExceedsScale: "Балл не может быть выше выбранной шкалы.",
      intakeYearRange: "Год поступления — от 2026 до 2035.",
      invalidDate: "Введите дату в формате ГГГГ-ММ-ДД.",
      examDateRequired: "Для сданного экзамена укажите дату.",
      examScoreInvalid: "Введите корректный балл.",
      examPending: "Добавьте экзамен или очистите незаполненные поля.",
      examAddEmpty: "Выберите экзамен и укажите балл",
      examScoreRange: (label: string, min: number, max: number) =>
        `${label}: балл должен быть от ${min} до ${max}.`,
      ieltsStep: "IELTS: балл с шагом 0.5.",
      aLevelGrade: "A-Level: выберите оценку A*, A, B, C, D, E или U.",
      subjectNotAllowed: "Предмет указывается только для AP и A-Level.",
      invalidType: "Некорректное значение.",
      tooSmall: "Значение слишком маленькое.",
      tooBig: "Значение слишком большое.",
    },
  },
  cv: {
    title: "Резюме",
    editor: "Редактор",
    preview: "Предпросмотр",
    downloadPdf: "Скачать PDF",
    headingsLang: "Язык заголовков",
    headingsRu: "RU",
    headingsEn: "EN",
    saving: "Сохраняю…",
    saved: "Сохранено",
    saveError: "Не удалось сохранить резюме.",
    showPlannedExams: "Показывать запланированные экзамены",
    plannedSuffix: "(план)",
    plannedSuffixEn: "(planned)",
    emailReadonly: "Email из аккаунта, его нельзя изменить здесь.",
    sections: {
      contacts: "Контакты",
      about: "О себе",
      education: "Образование",
      exams: "Экзамены",
      activities: "Активности",
      skills: "Навыки",
      languages: "Языки",
    },
    headingsEnLabels: {
      contacts: "Contact",
      about: "About",
      education: "Education",
      exams: "Exams",
      activities: "Activities",
      skills: "Skills",
      languages: "Languages",
    },
    fields: {
      email: "Email",
      phone: "Телефон",
      city: "Город",
      links: "Ссылки",
      linkLabel: "Название",
      linkUrl: "URL",
      addLink: "Добавить ссылку",
      summary: "О себе",
      summaryPlaceholder: "Коротко о целях и сильных сторонах",
      institution: "Школа или университет",
      grade: "Класс / курс",
      gpa: "GPA",
      skill: "Навык",
      addSkill: "Добавить навык",
      languageName: "Язык",
      languageLevel: "Уровень",
      addLanguage: "Добавить язык",
      activityType: "Тип",
      activityTitle: "Название",
      role: "Роль",
      organization: "Организация",
      description: "Описание",
      startDate: "Начало",
      endDate: "Окончание",
      achievement: "Результат",
      addActivity: "Добавить активность",
    },
    activityTypes: {
      olympiad: "Олимпиада",
      project: "Проект",
      volunteer: "Волонтёрство",
      work: "Работа / стажировка",
      sport: "Спорт",
      arts: "Творчество",
      other: "Другое",
    },
    emptyPreview: "Заполните разделы слева — здесь появится резюме.",
    errors: {
      titleRequired: "Укажите название активности.",
      invalidUrl: "Ссылка должна начинаться с http:// или https://.",
      urlTooLong: "Ссылка не длиннее 200 символов.",
    },
  },
  placeholders: {
    onboarding: {
      title: "Онбординг",
      description: "Здесь скоро появится анкета с вашими данными.",
    },
    profile: {
      title: "Профиль",
      description: "Здесь будет ваш профиль и CV.",
    },
    universities: {
      title: "Университеты",
      description: "Здесь появится подбор университетов.",
    },
    roadmap: {
      title: "План",
      description: "Здесь появится еженедельный план подготовки.",
    },
    tasks: {
      title: "Задачи",
      description: "Здесь появится трекер задач.",
    },
    agentPanel: {
      title: "AI-агент",
      description: "Скоро здесь появится помощник по поступлению.",
    },
  },
  errorPage: {
    title: "Что-то пошло не так",
    description: "Произошла непредвиденная ошибка. Попробуйте ещё раз.",
    retry: "Попробовать снова",
    backHome: "На главную",
  },
  notFoundPage: {
    title: "Страница не найдена",
    description: "Такой страницы не существует или она была перемещена.",
    backHome: "На главную",
  },
} as const;
